### ISSUE TITLE
Negative count

### ISSUE THREAD

**Issue by radoslawgrochowski** [pacdiv/regex.guide#14]
It is now possible to ask for negative count of selected quantifier.
e.g. "contain between -11 and -10 capital letters"

**Comment by pacdiv** [comment]
Hi @radoslawgrochowski,
Thanks for pointing this out!

I'll work on a contributing file and a changelog as soon as possible.
Meanwhile, would you like to submit a pull request or do you prefer I fix this issue?
I opened a new branch named 0.4.0 to gather the next fixes and features.

Let me know and thanks again for opening this issue!

**Comment by pacdiv** [comment]
**UI idea:**
The error message to display could be _“Minimum and maximum must be positive integers.”_.

**Comment by pacdiv** [comment]
Solved by the pull request #45.
