### ISSUE TITLE
Add a “reset” button

### ISSUE THREAD

**Issue by pacdiv** [pacdiv/regex.guide#40]
**Do you want to request a feature or report a bug?**
Feature.

**What is the expected behavior?**
As a user, I want to be able to reset my build by removing all the conditions I created. However, removing the conditions one by one can be binding. Under the _“Copy to clipboard”_ button could be added a _“Reset”_ or _“Reset conditions”_ transparent button to remove all these conditions with one click.

**Comment by drwm-base** [comment]
Hi pacdiv, I would like to attempt this feature!

**Comment by pacdiv** [comment]
Hi @drwm-base,

Sure, give it a try and submit a pull request! 🤗🎉
And let me know if anything is unclear with the core, unit tests or others.

**Comment by drwm-base** [comment]
Should the reset button also reset the sentence entered? Should it be a complete reset of the system or just the conditions?

**Comment by pacdiv** [comment]
Hi @drwm-base,

Yes, I think it should only reset the conditions. I think the most frequent case will be to restart building the regular expression (via these conditions) to match the already entered sentence. Maybe I'm wrong, what do you think?

**Comment by drwm-base** [comment]
I was just making sure I knew exactly what you wanted. Thanks for clarifying! Also please check out my pull request!

**Comment by pacdiv** [comment]
Solved by @drwm-base via the pull request #48.
Thanks a lot David! 👍
