### ISSUE TITLE
Code cleaning on ConditionInput and Playground components

### ISSUE THREAD

**Issue by pacdiv** [pacdiv/regex.guide#50]
**Do you want to request a feature or report a bug?**
Feature.

**What is the current behavior?**
Currently, the `ConditionInput` component contains some unused code:
- In the propTypes and the state, `exactQuantifierValue` and `queryString` are used in these functions below;
- The methods `onChange` and `onExactLimitTextFieldChange` are not used.

Also, the file `Playground.spec.js.backUp` is not used either.

**What is the expected behavior?**
These must be deleted.

**Comment by Scott09** [comment]
I'll get on this.

**Comment by pacdiv** [comment]
Solved by the pull request #71.
