### ISSUE TITLE
Replace the README image

### ISSUE THREAD

**Issue by pacdiv** [pacdiv/regex.guide#70]
**Do you want to request a feature or report a bug?**
Feature.

**What is the current behavior?**
The image placed at the beginning of the README and on the website’s homepage does not reflect how the app looks like today. 

**What is the expected behavior?**
This image must be replaced by the GIF below. However, the name should remain `readme-image.gif`. 

![58BE3101-8498-444B-8B93-30EE70830E5C](https://user-images.githubusercontent.com/25844965/66735320-531d1300-ee66-11e9-9125-307c10637e05.gif)

**Comment by Erick2280** [comment]
Hi! I'll take this issue :)

**Comment by pacdiv** [comment]
Welcome! 🤗
